In [1]:
#import sys
#!{sys.executable} -m pip install pandas
#!{sys.executable} -m pip install numpy

#import packages
import pandas as pd
import numpy as np

In [30]:
# start with first link as merger-base (here: Char.-Wil.)
berlin_fn = pd.read_csv("https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/charlottenburg-wilmersdorf.csv")

berlin_fn.drop("position", axis=1, inplace=True)
berlin_fn = berlin_fn.groupby(["vorname", "geschlecht"]).max()

link_list = ["https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/friedrichshain-kreuzberg.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/lichtenberg.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/marzahn-hellersdorf.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/mitte.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/neukoelln.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/pankow.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/reinickendorf.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/spandau.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/standesamt_i.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/steglitz-zehlendorf.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/tempelhof-schoeneberg.csv",
            "https://raw.githubusercontent.com/berlinonline/haeufige-vornamen-berlin/master/data/cleaned/2021/treptow-koepenick.csv"]

for link in link_list:
    names_temp = pd.read_csv(link)
    names_temp.drop("position", axis=1, inplace=True)
    names_temp = names_temp.groupby(["vorname", "geschlecht"]).max()
    berlin_fn = berlin_fn.merge(names_temp, on=["vorname", "geschlecht"], how="outer", validate="1:1")

berlin_fn = berlin_fn.reset_index()
berlin_fn = berlin_fn[["vorname", "geschlecht"]]

In [32]:
berlin_fn

       vorname geschlecht
0      Aaleyah          w
1      Aaliyah          w
2        Aanya          w
3        Aaron          m
4       Aarovi          w
...        ...        ...
13513    Yelle          m
13514    Yorik          m
13515   Zeljko          m
13516     Zola          m
13517  Şerrvan          m

[13518 rows x 2 columns]